### ISSUE TITLE
Running migrations shows a fatal error, but the process still completes

### ISSUE THREAD

**Issue by Tyrrrz** [passwordless/passwordless-server#130]
Basically this:

![image](https://github.com/passwordless/passwordless-server/assets/1935960/91d7fcc7-3e3e-446a-ad41-260c19ef9e1f)

Repro:
- Change directory to `src/AdminConsole`
- Run `dotnet ef migrations add FooBar --context SqliteConsoleDbContext`

It's not clear if the error is related, but it's labeled as fatal and looks distracting. Can we fix this?

/cc @jrmccannon

**Comment by jonashendrickx** [comment]
We probably have to catch it and hit return: [https://github.com/dotnet/efcore/issues/29809](https://github.com/dotnet/efcore/issues/29809)

**Comment by matt-goldman** [comment]
I came across this issue recently, it's alarming but actually harmless. It's because in the admin console you have a global exception handler: https://github.com/passwordless/passwordless-server/blob/7a18a53e1a752da87402d2e7b1806c23a07c5a61/src/AdminConsole/Program.cs#L40. The EF Core CLI terminates the host when it's finished getting configuration by throwing this exception, usually it handles this gracefully itself but if you have a global exception handler it will pick it up. As @jonashendrickx noted, covered in that GitHub conversation.

I found this thread when investigating this myself, I've written up my notes here in case it helps: https://goforgoldman.com/posts/ef-gotcha/
